version: '3.9'


services:
  testproject:
    image: testproject
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testproject
    expose:
      - ${TESTPROJECT_PORT}
    ports:
      - "${TESTPROJECT_PORT}:${TESTPROJECT_PORT}"
    volumes:
      - .:/app
    depends_on:
      - database
    env_file:
      - .env


  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    container_name: database
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ${DATABASE_DIR:-./database_data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "app"]
    env_file:
      - .env

