# Generated by Django 5.0.4 on 2024-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
