# Generated by Django 5.0.4 on 2024-04-18 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='links.link'),
            preserve_default=False,
        ),
    ]
