# Generated by Django 5.0.4 on 2024-04-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_link_image'),
        ('users', '0002_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.link'),
        ),
    ]
